version: '2'
services:
  examen2proyecto3v2-app:
    image: examen2proyecto3v2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://examen2proyecto3v2-mysql:3306/examen2proyecto3v2?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  examen2proyecto3v2-mysql:
    extends:
      file: mysql.yml
      service: examen2proyecto3v2-mysql
